### ISSUE TITLE
没有替换掉？

### ISSUE THREAD

**Issue by shi-an** [ghostflyby/LiteLoaderQQNT-Native-Menu#1]
![unknown_2024 02 25-17 30](https://github.com/ghostflyby/LiteLoaderQQNT-Native-Menu/assets/79352488/0f901282-1f77-44f7-ae93-487c82ac7a1f)

**Comment by ghostflyby** [comment]
fixed in https://github.com/ghostflyby/LiteLoaderQQNT-Native-Menu/releases/tag/1.0.2
